/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualrules;

import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Federico Garcia-Arevalo Calles
 */
public class ConditionFuzzyLogic extends javax.swing.JPanel {

    private static ArrayList _series;
    private static int _num_series;
    
    /**
     * Creates new form ConditionFuzzyLogic
     */
    public ConditionFuzzyLogic() {
        initComponents();
        _series = new ArrayList();
        _num_series = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _variable = new javax.swing.JLabel();
        _is = new javax.swing.JLabel();
        _label = new javax.swing.JPanel();

        _variable.setForeground(new java.awt.Color(0, 0, 204));
        _variable.setText("NameVariable");

        _is.setText("IS");

        javax.swing.GroupLayout _labelLayout = new javax.swing.GroupLayout(_label);
        _label.setLayout(_labelLayout);
        _labelLayout.setHorizontalGroup(
            _labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        _labelLayout.setVerticalGroup(
            _labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_variable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_is)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_variable)
                        .addComponent(_is))
                    .addComponent(_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void new_serie() {
        _series.add(new XYSeries("" + _num_series));
        _num_series++;
    }
    
    public void add(Number X, Number Y) {
        ((XYSeries) _series.get(_num_series - 1)).add(X,Y);
    }
    
    public void setVariable(String variable) {
        _variable.setText(variable);
    }
    
    public void createGraph() {
        _label.setSize(_label.getPreferredSize());
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        for(Object serie : _series){
            dataset.addSeries((XYSeries) serie);
        }
        
        JFreeChart chart = ChartFactory.createXYAreaChart("","","",dataset,
                                PlotOrientation.VERTICAL,false,false,false);
        
        ChartFrame frame = new ChartFrame("",chart);
        frame.pack();
        frame.setSize(_label.getSize());
        frame.setResizable(false);
        
        ChartPanel panel = frame.getChartPanel();
        panel.setPopupMenu(null);
        //panel.setDomainZoomable(false);
        //panel.setRangeZoomable(false);
        
        _label.add(panel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _is;
    private javax.swing.JPanel _label;
    private javax.swing.JLabel _variable;
    // End of variables declaration//GEN-END:variables
}
